In [1]:
# import necessary libraries 

import numpy as np
import pickle

In [5]:
# loading the pickle files

ohe_sex= pickle.load(open("models/ohe_sex.pkl","rb"))
ohe_embarked= pickle.load(open("models/ohe_embarked.pkl",'rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [17]:
# Assume user input

# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

display(test_input)

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [20]:
# as we did all the preprocessing steps in the other .ipynb file(ML_without_pipeline_project) we need to do the same for the test_input

test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))
print(test_input_sex)

test_input_embarked=ohe_embarked.transform(test_input[:,-1].reshape(1,1))
print(test_input_embarked)

test_input_age=test_input[:,2].reshape(1,1)
print(test_input_age)

[[0. 1.]]
[[0. 0. 1.]]
[[31.0]]


In [23]:
# concatinating all the test_input 

test_input_transformed=np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

#shape of test_input_transformed
test_input_transformed.shape


(1, 10)

In [24]:
clf.predict(test_input_transformed)

array([1], dtype=int64)